apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tc17hnq3h-nodejs 
  janus-idp.io/tekton: tc17hnq3h-nodejs
  backstage.io/kubernetes-id: tc17hnq3h-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tc17hnq3h-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml