apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tc17hnq3h-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tc17hnq3h-nodejs 
  name: tc17hnq3h-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tc17hnq3h-nodejs 
